[package]
name = "owl"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"

[dependencies]
bytemuck = { version = "*", optional = true }
num-traits = { version = "*", optional = true }

[features]
default = [ "std" ]
std = []
simd = []
